MODEL:
  WEIGHTS: "/home/live/RRPNv2/RRPN/data/models/X-101-32x8d.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.0025
  MAX_ITER: 30000
  STEPS: (10000, 20000)
  GAMMA: 0.1
DATASETS:
  TRAIN: ("nucoco_train",)
  TEST: ("nucoco_val",)
INPUT:
  MIN_SIZE_TRAIN: (900,)
  MAX_SIZE_TRAIN: 1600
  MIN_SIZE_TEST: 900
  MAX_SIZE_TEST: 1600
TEST:
  EVAL_PERIOD: 5000

PROPOSAL_FILES_TRAIN: "/home/live/RRPNv2/RRPN/data/nucoco/rrpn_proposals_train.pkl"
PROPOSAL_FILES_TEST: "/home/live/RRPNv2/RRPN/data/nucoco/rrpn_proposals_val.pkl"
