NUCOCO:
  VAL:
    IMG_DIR: "/clusterlivenfs/gnmp/RRPN/data/nucoco/annotations/rfdetr_large/val"
    ANNOT_DIR: "/clusterlivenfs/gnmp/RRPN/data/nucoco/annotations/rfdetr_large/annotations/instances_val.json"
  TRAIN:
    IMG_DIR: "/clusterlivenfs/gnmp/RRPN/data/nucoco/annotations/rfdetr_large/train"
    ANNOT_DIR: "/clusterlivenfs/gnmp/RRPN/data/nucoco/annotations/rfdetr_large/annotations/instances_train.json"

# NUCOCO:
  # VAL:
    # IMG_DIR: "/clusterlivenfs/gnmp/RRPN/data/nucoco/annotations/rfdetr/output_ann/val"
    # ANNOT_DIR: "/clusterlivenfs/gnmp/RRPN/data/nucoco/annotations/rfdetr/output_ann/annotations/instances_val.json"
  # TRAIN:
    # IMG_DIR: "/clusterlivenfs/gnmp/RRPN/data/nucoco/annotations/rfdetr/output_ann_train/train"
    # ANNOT_DIR: "/clusterlivenfs/gnmp/RRPN/data/nucoco/annotations/rfdetr/output_ann_train/annotations/instances_train.json"
